workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: 14.3.1
      cocoapods: 1.12.1
      java: 17
    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get
      - name: Build Android Release
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      # Add your publishing steps here (e.g., to Google Play, email, etc.)
      # For now, we'll just generate the APK as an artifact.


