workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m2
    working_directory: rabbit_coin_app # Set the working directory for the entire workflow
    environment:
      flutter: stable
      cocoapods: 1.12.1
      java: 17
    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get
      - name: Build Android Release
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk


