workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    working_directory: rabbit_coin_app
    environment:
      flutter: stable
      cocoapods: 1.12.1
      java: 17
    scripts:
      - name: Set up Flutter
        script: |
          export PATH="$FLUTTER_ROOT/bin:$PATH"
          flutter clean
          flutter pub get
      - name: Build Android Release
        script: |
          export PATH="$FLUTTER_ROOT/bin:$PATH"
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk


