workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: 14.3.1
      cocoapods: 1.12.1
      java: 17
    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get
      - name: Build Android Release
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    # Removed the publishing section as it was causing validation errors.
    # If you need publishing, you will need to add specific publishing steps here.


